//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public Bus()
        {
            this.Bus_Seat = new HashSet<Bus_Seat>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int bus_id { get; set; }
        public string bus_name { get; set; }
        public Nullable<int> bus_no { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.TimeSpan> departure_time { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> route_id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Route Route { get; set; }
        public virtual ICollection<Bus_Seat> Bus_Seat { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
