//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_Seat
    {
        public int id { get; set; }
        public string seat_no { get; set; }
        public Nullable<int> bus_id { get; set; }
        public string status { get; set; }
    
        public virtual Bus Bus { get; set; }
    }
}
