//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Buses = new HashSet<Bus>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int category_id { get; set; }
        public string type { get; set; }
        public Nullable<int> above_16 { get; set; }
        public Nullable<int> below_16 { get; set; }
        public Nullable<int> below_5 { get; set; }
    
        public virtual ICollection<Bus> Buses { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
