//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int reservation_id { get; set; }
        public int bus_id { get; set; }
        public int passenger_id { get; set; }
        public System.DateTime date_of_journey { get; set; }
        public int seat_no { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
