//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_price_details
    {
        public int tid { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> bus_id { get; set; }
        public Nullable<System.DateTime> date_of_journey { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual User_details User_details { get; set; }
    }
}
