//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_details
    {
        public User_details()
        {
            this.Passengers = new HashSet<Passenger>();
        }
    
        public int user_id { get; set; }
        public string name { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string email_id { get; set; }
        public long mobile_no { get; set; }
        public string password { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<Passenger> Passengers { get; set; }
    }
}
